language: csharp
solution: acastaner-mvc6.sln
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
branches:
  only:
    - master
    - release
mono: none
dotnet: 1.0.3
dist: trusty